// $Id$
// 
// Note:
// 
// Copyright (C) 2009 Full Name
//  
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;

namespace IrcShark.Extensions
{
	/// <summary>
	/// Instances of a class implementing this interface are generated by 
	/// an extension and offered to be used by other extensions
	/// </summary>
	/// <remarks>
	/// This interface is mostly for later use and should be implemented by ever class that should be used by other extensions</remarks>
	public interface IExtensionObject
	{
	}
}
