//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4927
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrcShark.Translation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IrcShark.Translation.Messages.de-DE", typeof(Messages_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Konfigurationsdatei nicht laden: {0} ähnelt.
        /// </summary>
        internal static string Error3001_CouldntLoadSettings {
            get {
                return ResourceManager.GetString("Error3001_CouldntLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte Konfigurationsdatei nicht speichern: {0} ähnelt.
        /// </summary>
        internal static string Error3002_CouldntSaveSettings {
            get {
                return ResourceManager.GetString("Error3002_CouldntSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Extension &quot;{0}&quot; konnte nicht geladen werden ähnelt.
        /// </summary>
        internal static string Error3003_ExtensionLoadFail {
            get {
                return ResourceManager.GetString("Error3003_ExtensionLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte IrcShark, mach dich bereit... ähnelt.
        /// </summary>
        internal static string Info1001_StartingIrcShark {
            get {
                return ResourceManager.GetString("Info1001_StartingIrcShark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfigurationsdatei erfolgreich geladen ähnelt.
        /// </summary>
        internal static string Info1002_LoadedSettings {
            get {
                return ResourceManager.GetString("Info1002_LoadedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterungs-Manager wird initialisiert... ähnelt.
        /// </summary>
        internal static string Info1003_InitialisingExtension {
            get {
                return ResourceManager.GetString("Info1003_InitialisingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfigurationsdatei erfolgreich gespeichert ähnelt.
        /// </summary>
        internal static string Info1004_SettingsSaved {
            get {
                return ResourceManager.GetString("Info1004_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IrcShark wurde in {0} Sekunden gestartet ähnelt.
        /// </summary>
        internal static string Info1005_StartedSeconds {
            get {
                return ResourceManager.GetString("Info1005_StartedSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IrcShark wird beendet ... bye bye ähnelt.
        /// </summary>
        internal static string Info1006_ShuttingDown {
            get {
                return ResourceManager.GetString("Info1006_ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versuche {0}: {1} ({2}) zu laden ähnelt.
        /// </summary>
        internal static string Info1007_TryToLoad {
            get {
                return ResourceManager.GetString("Info1007_TryToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Extension stehen zum laden bereit ähnelt.
        /// </summary>
        internal static string Info1008_ExtensionsWaitForLoading {
            get {
                return ResourceManager.GetString("Info1008_ExtensionsWaitForLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Erweiterung {0} wurde erfolgreich geladen. ähnelt.
        /// </summary>
        internal static string Info1009_ExtensionLoaded {
            get {
                return ResourceManager.GetString("Info1009_ExtensionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Erweiterung {0} wird bei nächten start von IrcShark entladen. ähnelt.
        /// </summary>
        internal static string Info1010_ExtensionMarkedForUnload {
            get {
                return ResourceManager.GetString("Info1010_ExtensionMarkedForUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konnte die Konfigurationsdatei &quot;{0}&quot; nicht finden, erstelle eine... ähnelt.
        /// </summary>
        internal static string Warning2001_SettingDoesentExist {
            get {
                return ResourceManager.GetString("Warning2001_SettingDoesentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Extension Ordner {0} existiert nicht und wird ignoriert ähnelt.
        /// </summary>
        internal static string Warning2002_ExtensionDirDoesntExist {
            get {
                return ResourceManager.GetString("Warning2002_ExtensionDirDoesntExist", resourceCulture);
            }
        }
    }
}
